# Generated by Django 3.2.25 on 2024-07-25 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20240725_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
    ]
