# Generated by Django 3.2.25 on 2024-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_contactgroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_id', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
